import '@/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

import { Providers } from '../components/Providers';

export const metadata: Metadata = {
  title: 'Tangled3 Next Example',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='en'
      className={`${GeistSans.variable}`}
    >
      <body className='bg-neutral-800'>
        <Providers>
          <main className='flex min-h-screen flex-col items-center text-white p-8'>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
