import '@/styles/globals.css';

import { GeistSans } from 'geist/font/sans';
import { type Metadata } from 'next';

import dynamic from 'next/dynamic';
import { Suspense } from 'react';
const Providers = dynamic(() => import('../components/Providers'), {
  ssr: false,
});

export const metadata: Metadata = {
  title: 'Tangled3 Next Example',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='en'
      className={`${GeistSans.variable}`}
    >
      <body className='bg-neutral-800 overflow-x-hidden w-[100vw]'>
        <Suspense>
          <Providers>
            <main className='flex min-h-screen w-full overflow-x-auto flex-col items-center text-white p-2'>
              {children}
            </main>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
